import type { SectorKey, SpecialDay, SpecialDayCategory, SelectedDayEntry } from "@/types/domain";
import { MAX_SELECTED_DAYS } from "@/lib/config";
import { slugify } from "@/lib/utils";

export const SPECIAL_DAY_CATEGORY_LABELS: Record<SpecialDayCategory, string> = {
  recommended: "Önerilenler",
  national: "Milli günler",
  holiday: "Bayramlar",
  religious: "Kandiller / dini günler",
  friday: "Cuma mesajları",
  popular: "Popüler özel günler",
  sectoral: "Sektörel günler",
  campaign: "Kampanya dönemleri",
};

export const SPECIAL_DAY_CATEGORY_ORDER: SpecialDayCategory[] = [
  "recommended",
  "national",
  "holiday",
  "religious",
  "friday",
  "popular",
  "sectoral",
  "campaign",
];

type DayInput = Omit<SpecialDay, "slug"> & { slug?: string };

function createDay(input: DayInput): SpecialDay {
  return {
    ...input,
    slug: input.slug ?? slugify(input.name),
  };
}

export const specialDaysCatalog: SpecialDay[] = [
  createDay({
    id: "new-year",
    name: "Yılbaşı",
    category: "recommended",
    dateType: "fixed",
    dateValue: "01-01",
    importance: "high",
    culturalContext: "Yeni başlangıç, teşekkür ve iyi dilek tonu uygundur.",
    popularUsages: ["Mutlu yıllar"],
    headlineAlternatives: ["Mutlu Yıllar", "Yeni Yıla Merhaba"],
    captionIdeas: [
      "Yeni yıla birlikte girerken bize güvenen tüm müşterilerimize teşekkür ederiz. Mutlu yıllar!",
      "2026 size sağlık, mutluluk ve bol kazanç getirsin. Yeni yılda da yanınızdayız.",
      "Yeni yıl kutlu olsun! Güzel anılar biriktirmeye devam edelim.",
    ],
    visualDirection: "modern kutlama, temiz kompozisyon",
    avoidRules: "aşırı klişe ve kalabalık konfeti",
    promptTemplate: "Create a premium Turkish New Year social media post for a small business.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "23-nisan",
    name: "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı",
    category: "national",
    dateType: "fixed",
    dateValue: "04-23",
    importance: "high",
    culturalContext: "Neşeli ama saygılı, çocuk odaklı ve umut veren ton.",
    popularUsages: ["23 Nisan kutlu olsun"],
    headlineAlternatives: ["23 Nisan Kutlu Olsun"],
    captionIdeas: ["Çocuklara yönelik umut dolu mesaj."],
    visualDirection: "renkli ama düzenli, modern çocuk teması",
    avoidRules: "aşırı oyuncak kalabalığı",
    promptTemplate: "Create a respectful and joyful Turkish 23 April social post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "1-mayis",
    name: "1 Mayıs Emek ve Dayanışma Günü",
    category: "national",
    dateType: "fixed",
    dateValue: "05-01",
    importance: "medium",
    culturalContext: "Saygılı ve birlik vurgulu ton.",
    popularUsages: ["1 Mayıs kutlu olsun"],
    headlineAlternatives: ["Emek ve Dayanışma Günü"],
    captionIdeas: ["Birlik ve emek odaklı kısa mesaj."],
    visualDirection: "güçlü tipografi, temiz modern kompozisyon",
    avoidRules: "politik parti çağrışımı",
    promptTemplate: "Create a respectful Turkish Labor Day social media post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "19-mayis",
    name: "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı",
    category: "national",
    dateType: "fixed",
    dateValue: "05-19",
    importance: "high",
    culturalContext: "Dinamik, genç ve saygılı ton.",
    popularUsages: ["19 Mayıs kutlu olsun"],
    headlineAlternatives: ["19 Mayıs Kutlu Olsun"],
    captionIdeas: ["Gençlik ve umut vurgulu kutlama."],
    visualDirection: "hareket hissi, güçlü tipografi",
    avoidRules: "yanlış bayrak ve bozuk yazı",
    promptTemplate: "Create a premium Turkish Youth and Sports Day post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "15-temmuz",
    name: "15 Temmuz Demokrasi ve Milli Birlik Günü",
    category: "national",
    dateType: "fixed",
    dateValue: "07-15",
    importance: "medium",
    culturalContext: "Saygılı ve ciddi ton.",
    popularUsages: ["Milli birlik günümüz"],
    headlineAlternatives: ["15 Temmuz Demokrasi ve Milli Birlik Günü"],
    captionIdeas: ["Anma ve birlik odaklı metin."],
    visualDirection: "güçlü ve sade kompozisyon",
    avoidRules: "aşırı kalabalık sahne",
    promptTemplate: "Create a respectful Turkish Democracy and National Unity Day post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "30-agustos",
    name: "30 Ağustos Zafer Bayramı",
    category: "national",
    dateType: "fixed",
    dateValue: "08-30",
    importance: "high",
    culturalContext: "Güçlü, kutlayıcı ve saygılı ton.",
    popularUsages: ["Zafer Bayramımız kutlu olsun"],
    headlineAlternatives: ["30 Ağustos Kutlu Olsun"],
    captionIdeas: ["Güçlü milli bayram kutlaması."],
    visualDirection: "kırmızı beyaz dengeli vurgu, modern tipografi",
    avoidRules: "yanlış bayrak, fazla karışıklık",
    promptTemplate: "Create a modern Turkish Victory Day social media post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "29-ekim",
    name: "29 Ekim Cumhuriyet Bayramı",
    category: "national",
    dateType: "fixed",
    dateValue: "10-29",
    importance: "high",
    culturalContext: "Türkiye'de çok önemli milli bayramdır; güçlü ve saygılı ton gerekir.",
    popularUsages: ["Cumhuriyet Bayramımız kutlu olsun"],
    headlineAlternatives: ["29 Ekim Kutlu Olsun", "Yaşasın Cumhuriyet"],
    captionIdeas: ["Güçlü Cumhuriyet mesajı."],
    visualDirection: "güçlü kırmızı-beyaz vurgular, temiz modern yerleşim, laik cumhuriyet estetiği",
    avoidRules: "yanlış bayrak, politik çağrışım, cami, minare, dini mimari, Osmanlı silueti",
    promptTemplate: "Create a respectful, modern, premium social media post for Turkey's Republic Day.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "ramadan-feast",
    name: "Ramazan Bayramı",
    category: "holiday",
    dateType: "movable",
    dateValue: "ramadan-feast",
    importance: "high",
    culturalContext: "İşletmenin müşterilerine saygılı, sıcak ve kutlayıcı bayram mesajı — ticari marka postu.",
    popularUsages: ["Ramazan Bayramımız mübarek olsun"],
    headlineAlternatives: ["Bayramınız Mübarek Olsun"],
    captionIdeas: ["Samimi ve saygılı bayram kutlaması."],
    visualDirection: "premium bayram grafiği; hilal motifi, marka renkleri, sektöre uygun kompozisyon — stok aile fotoğrafı değil",
    avoidRules: "karikatür dini semboller",
    promptTemplate: "Create a respectful, modern Turkish Ramadan Feast post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "kurban-bayrami",
    name: "Kurban Bayramı",
    category: "holiday",
    dateType: "movable",
    dateValue: "eid-al-adha",
    importance: "high",
    culturalContext: "İşletmenin müşterilerine saygılı Kurban Bayramı kutlaması — markalı sosyal medya grafiği.",
    popularUsages: ["Kurban Bayramınız mübarek olsun"],
    headlineAlternatives: ["Bayramınız Mübarek Olsun"],
    captionIdeas: ["Kurumsal ve samimi bayram metni."],
    visualDirection: "minimal dini dokunuşlar, sıcak tonlar",
    avoidRules: "aşırı karmaşa, uygunsuz semboller",
    promptTemplate: "Create a respectful, clean Turkish Eid al-Adha social media post.",
    isDefaultSelected: true,
  }),
  createDay({
    id: "regaib-kandili",
    name: "Regaib Kandili",
    category: "religious",
    dateType: "movable",
    dateValue: "regaib",
    importance: "medium",
    culturalContext: "Nazik ve saygılı ton.",
    popularUsages: ["Kandiliniz mübarek olsun"],
    headlineAlternatives: ["Regaib Kandiliniz Mübarek Olsun"],
    captionIdeas: ["Saygılı kandil mesajı."],
    visualDirection: "minimal islami desen, yumuşak ışık",
    avoidRules: "aşırı süsleme",
    promptTemplate: "Create a respectful Turkish Regaib Kandili post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "mirac-kandili",
    name: "Miraç Kandili",
    category: "religious",
    dateType: "movable",
    dateValue: "mirac",
    importance: "medium",
    culturalContext: "Nazik ve saygılı ton.",
    popularUsages: ["Kandiliniz mübarek olsun"],
    headlineAlternatives: ["Miraç Kandiliniz Mübarek Olsun"],
    captionIdeas: ["Saygılı kandil mesajı."],
    visualDirection: "minimal islami desen",
    avoidRules: "aşırı altın kullanım",
    promptTemplate: "Create a respectful Turkish Mirac Kandili post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "berat-kandili",
    name: "Berat Kandili",
    category: "religious",
    dateType: "movable",
    dateValue: "berat",
    importance: "medium",
    culturalContext: "Nazik ve saygılı ton.",
    popularUsages: ["Berat Kandiliniz mübarek olsun"],
    headlineAlternatives: ["Berat Kandiliniz Mübarek Olsun"],
    captionIdeas: ["Kısa ve saygılı kandil açıklaması."],
    visualDirection: "sakin, premium, huzurlu estetik",
    avoidRules: "fazla ışık patlaması",
    promptTemplate: "Create a respectful Turkish Berat Kandili post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "kadir-gecesi",
    name: "Kadir Gecesi",
    category: "religious",
    dateType: "movable",
    dateValue: "qadr",
    importance: "high",
    culturalContext: "Daha hassas ve saygılı ton.",
    popularUsages: ["Kadir Geceniz mübarek olsun"],
    headlineAlternatives: ["Kadir Geceniz Mübarek Olsun"],
    captionIdeas: ["Dini hassasiyeti yüksek kısa mesaj."],
    visualDirection: "huzurlu, temiz, yumuşak ışık",
    avoidRules: "aşırı gösteriş",
    promptTemplate: "Create a respectful Turkish Laylat al-Qadr post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "mevlid-kandili",
    name: "Mevlid Kandili",
    category: "religious",
    dateType: "movable",
    dateValue: "mawlid",
    importance: "medium",
    culturalContext: "Nazik ve saygılı ton.",
    popularUsages: ["Kandiliniz mübarek olsun"],
    headlineAlternatives: ["Mevlid Kandiliniz Mübarek Olsun"],
    captionIdeas: ["Kurumsal kandil mesajı."],
    visualDirection: "sade, zarif dini estetik",
    avoidRules: "bozuk Arapça/Türkçe metin",
    promptTemplate: "Create a respectful Turkish Mawlid Kandili post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "asure-gunu",
    name: "Aşure Günü",
    category: "religious",
    dateType: "movable",
    dateValue: "ashura",
    importance: "low",
    culturalContext: "Kültürel ve sıcak ton.",
    popularUsages: ["Aşure Gününüz hayırlı olsun"],
    headlineAlternatives: ["Aşure Günü"],
    captionIdeas: ["Sıcak topluluk mesajı."],
    visualDirection: "sıcak, topluluk hissi, sade",
    avoidRules: "fazla metin",
    promptTemplate: "Create a warm Turkish Ashura Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "uc-aylar-baslangici",
    name: "Üç Ayların Başlangıcı",
    category: "religious",
    dateType: "movable",
    dateValue: "three-months-start",
    importance: "medium",
    culturalContext: "Saygılı ve sakin ton.",
    popularUsages: ["Üç aylarınız hayırlı olsun"],
    headlineAlternatives: ["Üç Ayların Başlangıcı"],
    captionIdeas: ["Huzurlu ve saygılı mesaj."],
    visualDirection: "sakin, minimal dini estetik",
    avoidRules: "aşırı süsleme",
    promptTemplate: "Create a respectful Turkish Three Holy Months post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "hicri-yilbasi",
    name: "Hicri Yılbaşı",
    category: "religious",
    dateType: "movable",
    dateValue: "hijri-new-year",
    importance: "medium",
    culturalContext: "Saygılı ve sakin kutlama tonu.",
    popularUsages: ["Hicri yılınız mübarek olsun"],
    headlineAlternatives: ["Hicri Yılbaşı"],
    captionIdeas: ["Kısa ve saygılı kutlama."],
    visualDirection: "sade, huzurlu kompozisyon",
    avoidRules: "aşırı gösteriş",
    promptTemplate: "Create a respectful Turkish Hijri New Year post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "friday-blessing",
    name: "Hayırlı Cumalar",
    category: "friday",
    dateType: "manual",
    dateValue: "weekly-friday",
    importance: "medium",
    culturalContext: "İstediğiniz adet kadar cuma postu seçebilirsiniz (en fazla 4). Nazik ve saygılı ton.",
    popularUsages: ["Hayırlı Cumalar dileriz"],
    headlineAlternatives: ["Hayırlı Cumalar", "Bereketli Cumalar"],
    captionIdeas: ["Seçtiğiniz her cuma postu paket hakkınızdan 1 adet kullanır."],
    visualDirection: "soft geometric patterns, sade ışık",
    avoidRules: "aşırı dini sembol yoğunluğu",
    promptTemplate: "Create a respectful Turkish Friday greeting post for social media.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "valentines-day",
    name: "Sevgililer Günü",
    category: "popular",
    dateType: "fixed",
    dateValue: "02-14",
    importance: "medium",
    culturalContext: "Sıcak ve modern ton.",
    popularUsages: ["Sevgililer Gününüz kutlu olsun"],
    headlineAlternatives: ["Sevgililer Günü"],
    captionIdeas: ["Samimi ama abartısız kutlama."],
    visualDirection: "minimal romantik dokunuşlar",
    avoidRules: "aşırı klişe kalp yağmuru",
    promptTemplate: "Create a modern Turkish Valentine's Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "womens-day",
    name: "8 Mart Dünya Kadınlar Günü",
    category: "popular",
    dateType: "fixed",
    dateValue: "03-08",
    importance: "high",
    culturalContext: "Güçlendirici ve saygılı ton.",
    popularUsages: ["Dünya Kadınlar Günü kutlu olsun"],
    headlineAlternatives: ["8 Mart Dünya Kadınlar Günü"],
    captionIdeas: ["Takdir ve güç odaklı kısa metin."],
    visualDirection: "güçlü ama zarif estetik",
    avoidRules: "yüzeysel klişeler",
    promptTemplate: "Create an empowering Turkish Women's Day social media post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "mothers-day",
    name: "Anneler Günü",
    category: "popular",
    dateType: "movable",
    dateValue: "mothers-day",
    importance: "high",
    culturalContext: "Duygusal ama ölçülü, sıcak ve teşekkür odaklı olmalı.",
    popularUsages: ["Anneler Gününüz kutlu olsun"],
    headlineAlternatives: ["Anneler Gününüz Kutlu Olsun"],
    captionIdeas: ["Sevgi ve teşekkür odaklı kısa mesaj."],
    visualDirection: "çiçeksi ama modern, yumuşak, sıcak",
    avoidRules: "aşırı pembe klişesi",
    promptTemplate: "Create a warm and modern Mother's Day post in Turkish.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "fathers-day",
    name: "Babalar Günü",
    category: "popular",
    dateType: "movable",
    dateValue: "fathers-day",
    importance: "medium",
    culturalContext: "Sıcak ve teşekkür odaklı ton.",
    popularUsages: ["Babalar Gününüz kutlu olsun"],
    headlineAlternatives: ["Babalar Gününüz Kutlu Olsun"],
    captionIdeas: ["Takdir ve teşekkür odaklı açıklama."],
    visualDirection: "temiz ve modern",
    avoidRules: "fazla klişe aksesuar",
    promptTemplate: "Create a modern Turkish Father's Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "teachers-day",
    name: "Öğretmenler Günü",
    category: "popular",
    dateType: "fixed",
    dateValue: "11-24",
    importance: "high",
    culturalContext: "Saygılı ve teşekkür odaklı ton.",
    popularUsages: ["Öğretmenler Gününüz kutlu olsun"],
    headlineAlternatives: ["24 Kasım Öğretmenler Günü"],
    captionIdeas: ["Emek ve teşekkür vurgulu açıklama."],
    visualDirection: "eğitim temalı sade görsel dil",
    avoidRules: "fazla çocukça tasarım",
    promptTemplate: "Create a respectful Turkish Teachers' Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "world-coffee-day",
    name: "Dünya Kahve Günü",
    category: "popular",
    dateType: "fixed",
    dateValue: "10-01",
    importance: "medium",
    culturalContext: "Sıcak ve davetkar ton.",
    popularUsages: ["Dünya Kahve Günü kutlu olsun"],
    headlineAlternatives: ["Dünya Kahve Günü"],
    captionIdeas: ["Kahve severlere sıcak mesaj."],
    visualDirection: "kahve tonları, sıcak ve cozy",
    avoidRules: "karanlık, iştah kapatan görseller",
    promptTemplate: "Create a warm Turkish World Coffee Day social post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "animal-protection-day",
    name: "Dünya Hayvanları Koruma Günü",
    category: "popular",
    dateType: "fixed",
    dateValue: "10-04",
    importance: "medium",
    culturalContext: "Sıcak, duyarlı ve pozitif ton.",
    popularUsages: ["Dünya Hayvanları Koruma Günü"],
    headlineAlternatives: ["Hayvanları Koruyalım"],
    captionIdeas: ["Duyarlılık ve sevgi odaklı mesaj."],
    visualDirection: "sıcak, sevecen, temiz",
    avoidRules: "üzücü veya sert görseller",
    promptTemplate: "Create a warm Turkish World Animal Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "black-friday",
    name: "Black Friday",
    category: "campaign",
    dateType: "fixed",
    dateValue: "11-29",
    importance: "medium",
    culturalContext: "Satış odaklı ama premium ton.",
    popularUsages: ["Black Friday fırsatları başladı"],
    headlineAlternatives: ["Black Friday", "Haftanın Fırsatları"],
    captionIdeas: ["Kısa kampanya metni."],
    visualDirection: "yüksek kontrast, premium kampanya estetiği",
    avoidRules: "ucuz indirim afişi hissi",
    promptTemplate: "Create a premium Black Friday social media post in Turkish.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "back-to-school",
    name: "Okula Dönüş",
    category: "campaign",
    dateType: "manual",
    dateValue: "back-to-school",
    importance: "medium",
    culturalContext: "Dinamik ve temiz ton.",
    popularUsages: ["Yeni döneme hazırız"],
    headlineAlternatives: ["Okula Dönüş"],
    captionIdeas: ["Hazırlık ve yeni dönem mesajı."],
    visualDirection: "düzenli, modern, genç enerji",
    avoidRules: "fazla çocukça karakterler",
    promptTemplate: "Create a clean Turkish back-to-school campaign post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "new-season",
    name: "Yeni Sezon",
    category: "campaign",
    dateType: "manual",
    dateValue: "new-season",
    importance: "medium",
    culturalContext: "Taze başlangıç ve yenilik vurgusu.",
    popularUsages: ["Yeni sezon başladı"],
    headlineAlternatives: ["Yeni Sezon"],
    captionIdeas: ["Yenilik ve tazelik mesajı."],
    visualDirection: "modern, enerjik, temiz",
    avoidRules: "karmaşık kampanya görseli",
    promptTemplate: "Create a fresh new season campaign post in Turkish.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "summer-season",
    name: "Yaz Sezonu",
    category: "campaign",
    dateType: "manual",
    dateValue: "summer",
    importance: "medium",
    culturalContext: "Enerjik ve sıcak yaz tonu.",
    popularUsages: ["Yaz sezonu başladı"],
    headlineAlternatives: ["Yaz Sezonu"],
    captionIdeas: ["Yaz kampanyası mesajı."],
    visualDirection: "parlak, sıcak, enerjik",
    avoidRules: "aşırı parlak ve okunaksız metin",
    promptTemplate: "Create a vibrant Turkish summer season post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "winter-campaign",
    name: "Kış Kampanyası",
    category: "campaign",
    dateType: "manual",
    dateValue: "winter",
    importance: "medium",
    culturalContext: "Sıcak ve davetkar kış tonu.",
    popularUsages: ["Kış kampanyamız başladı"],
    headlineAlternatives: ["Kış Kampanyası"],
    captionIdeas: ["Kış fırsatları mesajı."],
    visualDirection: "sıcak tonlar, premium kış estetiği",
    avoidRules: "karanlık ve kasvetli görünüm",
    promptTemplate: "Create a cozy Turkish winter campaign post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "year-end-campaign",
    name: "Yıl Sonu Kampanyası",
    category: "campaign",
    dateType: "manual",
    dateValue: "year-end",
    importance: "medium",
    culturalContext: "Teşekkür ve yıl sonu fırsatları tonu.",
    popularUsages: ["Yıl sonu fırsatları"],
    headlineAlternatives: ["Yıl Sonu Kampanyası"],
    captionIdeas: ["Teşekkür ve fırsat mesajı."],
    visualDirection: "premium, kutlama ve kampanya dengesi",
    avoidRules: "aşırı kalabalık görsel",
    promptTemplate: "Create a premium Turkish year-end campaign post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "medical-day",
    name: "Tıp Bayramı",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "03-14",
    importance: "medium",
    culturalContext: "Saygılı ve güven veren sağlık tonu.",
    popularUsages: ["Tıp Bayramı kutlu olsun"],
    headlineAlternatives: ["14 Mart Tıp Bayramı"],
    captionIdeas: ["Sağlık emekçilerine teşekkür."],
    visualDirection: "temiz, profesyonel, güven veren",
    avoidRules: "rahatsız edici medikal detay",
    promptTemplate: "Create a respectful Turkish Medical Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "dentists-day",
    name: "Diş Hekimleri Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "11-22",
    importance: "medium",
    culturalContext: "Güven veren ve profesyonel ton.",
    popularUsages: ["Diş Hekimleri Günü kutlu olsun"],
    headlineAlternatives: ["Diş Hekimleri Günü"],
    captionIdeas: ["Güven ve teşekkür mesajı."],
    visualDirection: "temiz, hijyenik, modern",
    avoidRules: "rahatsız edici diş görselleri",
    promptTemplate: "Create a clean Turkish Dentists Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "pharmacists-day",
    name: "Eczacılar Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "05-14",
    importance: "medium",
    culturalContext: "Saygılı ve güven veren ton.",
    popularUsages: ["Eczacılar Günü kutlu olsun"],
    headlineAlternatives: ["Eczacılar Günü"],
    captionIdeas: ["Teşekkür ve güven mesajı."],
    visualDirection: "temiz, profesyonel",
    avoidRules: "aşırı medikal karmaşa",
    promptTemplate: "Create a respectful Turkish Pharmacists Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "lawyers-day",
    name: "Avukatlar Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "04-05",
    importance: "medium",
    culturalContext: "Kurumsal ve saygılı ton.",
    popularUsages: ["Avukatlar Günü kutlu olsun"],
    headlineAlternatives: ["Avukatlar Günü"],
    captionIdeas: ["Adalet ve emek vurgusu."],
    visualDirection: "kurumsal, güven veren",
    avoidRules: "ağır ve karanlık görünüm",
    promptTemplate: "Create a corporate Turkish Lawyers Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "architects-day",
    name: "Mimarlar Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "10-13",
    importance: "medium",
    culturalContext: "Modern ve yaratıcı ton.",
    popularUsages: ["Mimarlar Günü kutlu olsun"],
    headlineAlternatives: ["Mimarlar Günü"],
    captionIdeas: ["Tasarım ve emek vurgusu."],
    visualDirection: "modern mimari çizgiler",
    avoidRules: "karmaşık teknik çizimler",
    promptTemplate: "Create a modern Turkish Architects Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "accountants-day",
    name: "Muhasebeciler Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "03-01",
    importance: "low",
    culturalContext: "Kurumsal ve teşekkür odaklı ton.",
    popularUsages: ["Muhasebeciler Günü kutlu olsun"],
    headlineAlternatives: ["Muhasebeciler Günü"],
    captionIdeas: ["Emek ve güven mesajı."],
    visualDirection: "kurumsal, düzenli, temiz",
    avoidRules: "sıkıcı ofis klişesi",
    promptTemplate: "Create a corporate Turkish Accountants Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "nurses-day",
    name: "Hemşireler Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "05-12",
    importance: "medium",
    culturalContext: "Saygılı ve teşekkür odaklı ton.",
    popularUsages: ["Hemşireler Günü kutlu olsun"],
    headlineAlternatives: ["Hemşireler Günü"],
    captionIdeas: ["Emek ve şefkat vurgusu."],
    visualDirection: "sıcak, güven veren, temiz",
    avoidRules: "rahatsız edici hastane görüntüleri",
    promptTemplate: "Create a respectful Turkish Nurses Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "world-physio-day",
    name: "Dünya Fizyoterapistler Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "09-08",
    importance: "medium",
    culturalContext: "Sağlık ve hareket odaklı pozitif ton.",
    popularUsages: ["Dünya Fizyoterapistler Günü"],
    headlineAlternatives: ["Fizyoterapistler Günü"],
    captionIdeas: ["Sağlıklı hareket vurgusu."],
    visualDirection: "dinamik, temiz, sağlıklı",
    avoidRules: "ağrı veya sakatlık vurgusu",
    promptTemplate: "Create a positive Turkish World Physiotherapy Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "world-vet-day",
    name: "Dünya Veteriner Hekimler Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "04-28",
    importance: "medium",
    culturalContext: "Sıcak ve duyarlı ton.",
    popularUsages: ["Veteriner Hekimler Günü kutlu olsun"],
    headlineAlternatives: ["Dünya Veteriner Hekimler Günü"],
    captionIdeas: ["Hayvan sevgisi ve teşekkür."],
    visualDirection: "sıcak, sevecen, temiz",
    avoidRules: "üzücü hayvan görselleri",
    promptTemplate: "Create a warm Turkish World Veterinary Day post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "tourism-week",
    name: "Turizm Haftası",
    category: "sectoral",
    dateType: "manual",
    dateValue: "tourism-week",
    importance: "medium",
    culturalContext: "Davetkar ve keşif odaklı ton.",
    popularUsages: ["Turizm Haftası kutlu olsun"],
    headlineAlternatives: ["Turizm Haftası"],
    captionIdeas: ["Keşif ve davet mesajı."],
    visualDirection: "seyahat, şehir, doğa dengesi",
    avoidRules: "stok fotoğraf hissi",
    promptTemplate: "Create an inviting Turkish Tourism Week post.",
    isDefaultSelected: false,
  }),
  createDay({
    id: "world-beauty-day",
    name: "Dünya Güzellik Günü",
    category: "sectoral",
    dateType: "fixed",
    dateValue: "09-09",
    importance: "medium",
    culturalContext: "Zarif ve premium güzellik tonu.",
    popularUsages: ["Dünya Güzellik Günü"],
    headlineAlternatives: ["Dünya Güzellik Günü"],
    captionIdeas: ["Bakım ve özgüven vurgusu."],
    visualDirection: "zarif, premium, temiz",
    avoidRules: "aşırı filtre ve yapay görünüm",
    promptTemplate: "Create an elegant Turkish World Beauty Day post.",
    isDefaultSelected: false,
  }),
];

export const SECTOR_SPECIAL_DAY_IDS: Partial<Record<SectorKey, string[]>> = {
  beauty: ["world-beauty-day", "womens-day", "mothers-day", "valentines-day"],
  cafe: ["world-coffee-day", "valentines-day", "mothers-day"],
  dental: ["dentists-day", "medical-day"],
  "real-estate": ["new-season", "summer-season"],
  education: ["teachers-day", "back-to-school", "23-nisan"],
  boutique: ["black-friday", "new-season", "valentines-day", "womens-day"],
  "auto-service": ["summer-season", "winter-campaign"],
  fitness: ["world-physio-day", "summer-season", "new-year"],
  nutrition: ["world-physio-day", "womens-day"],
  agency: ["new-season", "black-friday", "year-end-campaign"],
  veterinary: ["world-vet-day", "animal-protection-day"],
  law: ["lawyers-day"],
  accounting: ["accountants-day", "year-end-campaign"],
  hotel: ["tourism-week", "summer-season", "new-season"],
  photography: ["new-season", "valentines-day", "womens-day"],
  construction: ["architects-day", "new-season"],
  cleaning: ["new-season", "winter-campaign"],
  "flower-gift": ["valentines-day", "mothers-day", "womens-day"],
  barber: ["fathers-day", "womens-day"],
  jewelry: ["valentines-day", "mothers-day", "womens-day"],
  ecommerce: ["black-friday", "year-end-campaign", "new-season"],
  other: ["new-season", "black-friday"],
};

const FILL_PRIORITY: SpecialDayCategory[] = [
  "friday",
  "religious",
  "popular",
  "campaign",
  "sectoral",
  "national",
  "recommended",
];

export function getDefaultSelectedDays(): SelectedDayEntry[] {
  return specialDaysCatalog
    .filter((day) => day.isDefaultSelected)
    .map((day) => ({ dayId: day.id, quantity: 1 }));
}

export function getSpecialDayById(dayId: string) {
  return specialDaysCatalog.find((day) => day.id === dayId);
}

function addEntryIfFits(
  result: SelectedDayEntry[],
  dayId: string,
  quantity = 1,
  max = MAX_SELECTED_DAYS,
) {
  const used = result.reduce((sum, item) => sum + item.quantity, 0);
  if (used + quantity > max) return;
  if (result.some((item) => item.dayId === dayId)) return;
  result.push({ dayId, quantity });
}

export function buildAutoSelectedDays(sector?: SectorKey, max = MAX_SELECTED_DAYS) {
  const result: SelectedDayEntry[] = [];

  for (const day of specialDaysCatalog.filter((item) => item.isDefaultSelected)) {
    addEntryIfFits(result, day.id, 1, max);
  }

  if (sector) {
    for (const dayId of SECTOR_SPECIAL_DAY_IDS[sector] ?? []) {
      addEntryIfFits(result, dayId, 1, max);
    }
  }

  return result;
}

/** Hızlı form: sektöre göre 30 güne otomatik doldurur. */
export function buildQuickPackageDays(sector?: SectorKey, max = MAX_SELECTED_DAYS) {
  const result = buildAutoSelectedDays(sector, max);
  let used = result.reduce((sum, item) => sum + item.quantity, 0);

  for (const category of FILL_PRIORITY) {
    if (used >= max) break;
    for (const day of specialDaysCatalog.filter((item) => item.category === category)) {
      if (used >= max) break;
      const before = used;
      addEntryIfFits(result, day.id, 1, max);
      used = result.reduce((sum, item) => sum + item.quantity, 0);
      if (used === before) continue;
    }
  }

  for (const day of specialDaysCatalog) {
    if (used >= max) break;
    const before = used;
    addEntryIfFits(result, day.id, 1, max);
    used = result.reduce((sum, item) => sum + item.quantity, 0);
    if (used === before) continue;
  }

  return result;
}
