insert into special_days (
  name, slug, category, date_type, date_value, importance, cultural_context,
  popular_usages, headline_alternatives, caption_ideas, visual_direction,
  avoid_rules, prompt_template, is_default_selected
)
values
  ('Yılbaşı', 'yilbasi', 'recommended', 'fixed', '01-01', 'high',
    'Yeni başlangıç ve iyi dilek tonu uygundur.',
    '["Mutlu yıllar"]'::jsonb,
    '["Mutlu Yıllar", "Yeni Yıla Merhaba"]'::jsonb,
    '["Teşekkür ve iyi dilek odaklı açıklama"]'::jsonb,
    'yeşil-beyaz, modern kutlama, temiz kompozisyon',
    'aşırı klişe ve kalabalık konfeti',
    'Create a premium Turkish New Year social media post for a small business.',
    true),
  ('Ramazan Bayramı', 'ramazan-bayrami', 'holiday', 'movable', 'ramadan-feast', 'high',
    'Saygılı, sıcak ve kutlayıcı ton kullanılmalı.',
    '["Ramazan Bayramımız mübarek olsun"]'::jsonb,
    '["Bayramınız Mübarek Olsun"]'::jsonb,
    '["Nazik ve kurumsal kutlama açıklaması"]'::jsonb,
    'zarif hilal dokunuşu, sıcak ışık, premium düzen',
    'karikatür dini öğeler',
    'Create a respectful, modern Turkish Ramadan Feast post.',
    true),
  ('Kurban Bayramı', 'kurban-bayrami', 'holiday', 'movable', 'eid-al-adha', 'high',
    'Saygılı ve sıcak bir bayram tonu kullanılmalı.',
    '["Kurban Bayramınız mübarek olsun"]'::jsonb,
    '["Bayramınız Mübarek Olsun"]'::jsonb,
    '["Kurumsal ve samimi bayram metni"]'::jsonb,
    'minimal dini dokunuşlar, sıcak tonlar',
    'aşırı karmaşa, uygunsuz semboller',
    'Create a respectful, clean Turkish Eid al-Adha social media post.',
    true),
  ('23 Nisan Ulusal Egemenlik ve Çocuk Bayramı', '23-nisan', 'national', 'fixed', '04-23', 'high',
    'Neşeli ama saygılı, çocuk odaklı ve umut veren ton.',
    '["23 Nisan kutlu olsun"]'::jsonb,
    '["23 Nisan Kutlu Olsun"]'::jsonb,
    '["Çocuklara yönelik umut dolu mesaj"]'::jsonb,
    'renkli ama düzenli, modern çocuk teması',
    'aşırı oyuncak kalabalığı',
    'Create a respectful and joyful Turkish 23 April social post.',
    true),
  ('1 Mayıs Emek ve Dayanışma Günü', '1-mayis', 'national', 'fixed', '05-01', 'medium',
    'Saygılı ve birlik vurgulu ton.',
    '["1 Mayıs kutlu olsun"]'::jsonb,
    '["Emek ve Dayanışma Günü"]'::jsonb,
    '["Birlik ve emek odaklı kısa mesaj"]'::jsonb,
    'güçlü tipografi, temiz modern kompozisyon',
    'politik parti çağrışımı',
    'Create a respectful Turkish Labor Day social media post.',
    true),
  ('19 Mayıs Atatürk’ü Anma, Gençlik ve Spor Bayramı', '19-mayis', 'national', 'fixed', '05-19', 'high',
    'Dinamik, genç ve saygılı ton.',
    '["19 Mayıs kutlu olsun"]'::jsonb,
    '["19 Mayıs Kutlu Olsun"]'::jsonb,
    '["Gençlik ve umut vurgulu kutlama"]'::jsonb,
    'hareket hissi, güçlü tipografi',
    'yanlış bayrak ve bozuk yazı',
    'Create a premium Turkish Youth and Sports Day post.',
    true),
  ('15 Temmuz Demokrasi ve Milli Birlik Günü', '15-temmuz', 'national', 'fixed', '07-15', 'medium',
    'Saygılı ve ciddi ton.',
    '["Milli birlik günümüz"]'::jsonb,
    '["15 Temmuz Demokrasi ve Milli Birlik Günü"]'::jsonb,
    '["Anma ve birlik odaklı metin"]'::jsonb,
    'güçlü ve sade kompozisyon',
    'aşırı kalabalık sahne',
    'Create a respectful Turkish Democracy and National Unity Day post.',
    true),
  ('30 Ağustos Zafer Bayramı', '30-agustos', 'national', 'fixed', '08-30', 'high',
    'Güçlü, kutlayıcı ve saygılı ton.',
    '["Zafer Bayramımız kutlu olsun"]'::jsonb,
    '["30 Ağustos Kutlu Olsun"]'::jsonb,
    '["Güçlü milli bayram kutlaması"]'::jsonb,
    'kırmızı beyaz dengeli vurgu, modern tipografi',
    'yanlış bayrak, fazla karışıklık',
    'Create a modern Turkish Victory Day social media post.',
    true),
  ('29 Ekim Cumhuriyet Bayramı', '29-ekim-cumhuriyet-bayrami', 'national', 'fixed', '10-29', 'high',
    'Türkiye’de çok önemli milli bayramdır; güçlü ve saygılı ton gerekir.',
    '["Cumhuriyet Bayramımız kutlu olsun"]'::jsonb,
    '["29 Ekim Kutlu Olsun", "Yaşasın Cumhuriyet"]'::jsonb,
    '["Güçlü Cumhuriyet mesajı"]'::jsonb,
    'güçlü kırmızı-beyaz vurgular, temiz modern yerleşim',
    'yanlış bayrak, politik çağrışım',
    'Create a respectful, modern, premium social media post for Turkey''s Republic Day.',
    true),
  ('Regaib Kandili', 'regaib-kandili', 'religious', 'movable', 'regaib', 'medium',
    'Nazik ve saygılı ton.',
    '["Kandiliniz mübarek olsun"]'::jsonb,
    '["Regaib Kandiliniz Mübarek Olsun"]'::jsonb,
    '["Saygılı kandil mesajı"]'::jsonb,
    'minimal islami desen, yumuşak ışık',
    'aşırı süsleme',
    'Create a respectful Turkish Regaib Kandili post.',
    false),
  ('Miraç Kandili', 'mirac-kandili', 'religious', 'movable', 'mirac', 'medium',
    'Nazik ve saygılı ton.',
    '["Kandiliniz mübarek olsun"]'::jsonb,
    '["Miraç Kandiliniz Mübarek Olsun"]'::jsonb,
    '["Saygılı kandil mesajı"]'::jsonb,
    'minimal islami desen',
    'aşırı altın kullanım',
    'Create a respectful Turkish Mirac Kandili post.',
    false),
  ('Berat Kandili', 'berat-kandili', 'religious', 'movable', 'berat', 'medium',
    'Nazik ve saygılı ton.',
    '["Berat Kandiliniz mübarek olsun"]'::jsonb,
    '["Berat Kandiliniz Mübarek Olsun"]'::jsonb,
    '["Kısa ve saygılı kandil açıklaması"]'::jsonb,
    'sakin, premium, huzurlu estetik',
    'fazla ışık patlaması',
    'Create a respectful Turkish Berat Kandili post.',
    false),
  ('Kadir Gecesi', 'kadir-gecesi', 'religious', 'movable', 'qadr', 'high',
    'Daha hassas ve saygılı ton.',
    '["Kadir Geceniz mübarek olsun"]'::jsonb,
    '["Kadir Geceniz Mübarek Olsun"]'::jsonb,
    '["Dini hassasiyeti yüksek kısa mesaj"]'::jsonb,
    'huzurlu, temiz, yumuşak ışık',
    'aşırı gösteriş',
    'Create a respectful Turkish Laylat al-Qadr post.',
    false),
  ('Mevlid Kandili', 'mevlid-kandili', 'religious', 'movable', 'mawlid', 'medium',
    'Nazik ve saygılı ton.',
    '["Kandiliniz mübarek olsun"]'::jsonb,
    '["Mevlid Kandiliniz Mübarek Olsun"]'::jsonb,
    '["Kurumsal kandil mesajı"]'::jsonb,
    'sade, zarif dini estetik',
    'bozuk Arapça/Türkçe metin',
    'Create a respectful Turkish Mawlid Kandili post.',
    false),
  ('Aşure Günü', 'asure-gunu', 'religious', 'movable', 'ashura', 'low',
    'Kültürel ve sıcak ton.',
    '["Aşure Gününüz hayırlı olsun"]'::jsonb,
    '["Aşure Günü"]'::jsonb,
    '["Sıcak topluluk mesajı"]'::jsonb,
    'sıcak, topluluk hissi, sade',
    'fazla metin',
    'Create a warm Turkish Ashura Day post.',
    false),
  ('Hayırlı Cumalar', 'hayirli-cumalar', 'friday', 'manual', 'weekly-friday', 'medium',
    'Nazik, sıcak, abartısız ve saygılı ton tercih edilmeli.',
    '["Hayırlı Cumalar dileriz"]'::jsonb,
    '["Hayırlı Cumalar", "Bereketli Cumalar"]'::jsonb,
    '["1 seçim hakkı ile 4 farklı cuma postu"]'::jsonb,
    'soft geometric patterns, sade ışık',
    'aşırı dini sembol yoğunluğu',
    'Create a respectful Turkish Friday greeting post for social media.',
    false),
  ('Sevgililer Günü', 'sevgililer-gunu', 'popular', 'fixed', '02-14', 'medium',
    'Sıcak ve modern ton.',
    '["Sevgililer Gününüz kutlu olsun"]'::jsonb,
    '["Sevgililer Günü"]'::jsonb,
    '["Samimi ama abartısız kutlama"]'::jsonb,
    'minimal romantik dokunuşlar',
    'aşırı klişe kalp yağmuru',
    'Create a modern Turkish Valentine''s Day post.',
    false),
  ('8 Mart Dünya Kadınlar Günü', 'kadinlar-gunu', 'popular', 'fixed', '03-08', 'high',
    'Güçlendirici ve saygılı ton.',
    '["Dünya Kadınlar Günü kutlu olsun"]'::jsonb,
    '["8 Mart Dünya Kadınlar Günü"]'::jsonb,
    '["Takdir ve güç odaklı kısa metin"]'::jsonb,
    'güçlü ama zarif estetik',
    'yüzeysel klişeler',
    'Create an empowering Turkish Women''s Day social media post.',
    false),
  ('Anneler Günü', 'anneler-gunu', 'popular', 'movable', 'mothers-day', 'high',
    'Duygusal ama ölçülü ton.',
    '["Anneler Gününüz kutlu olsun"]'::jsonb,
    '["Anneler Gününüz Kutlu Olsun"]'::jsonb,
    '["Sevgi ve teşekkür odaklı açıklama"]'::jsonb,
    'sıcak ve zarif',
    'aşırı pembe klişesi',
    'Create a warm and modern Mother''s Day post in Turkish.',
    false),
  ('Babalar Günü', 'babalar-gunu', 'popular', 'movable', 'fathers-day', 'medium',
    'Sıcak ve teşekkür odaklı ton.',
    '["Babalar Gününüz kutlu olsun"]'::jsonb,
    '["Babalar Gününüz Kutlu Olsun"]'::jsonb,
    '["Takdir ve teşekkür odaklı açıklama"]'::jsonb,
    'temiz ve modern',
    'fazla klişe aksesuar',
    'Create a modern Turkish Father''s Day post.',
    false),
  ('Öğretmenler Günü', 'ogretmenler-gunu', 'popular', 'fixed', '11-24', 'high',
    'Saygılı ve teşekkür odaklı ton.',
    '["Öğretmenler Gününüz kutlu olsun"]'::jsonb,
    '["24 Kasım Öğretmenler Günü"]'::jsonb,
    '["Emek ve teşekkür vurgulu açıklama"]'::jsonb,
    'eğitim temalı sade görsel dil',
    'fazla çocukça tasarım',
    'Create a respectful Turkish Teachers'' Day post.',
    false),
  ('Black Friday', 'black-friday', 'campaign', 'fixed', '11-29', 'medium',
    'Satış odaklı ama premium ton.',
    '["Black Friday fırsatları başladı"]'::jsonb,
    '["Black Friday", "Haftanın Fırsatları"]'::jsonb,
    '["Kısa kampanya metni"]'::jsonb,
    'yüksek kontrast, premium kampanya estetiği',
    'ucuz indirim afişi hissi',
    'Create a premium Black Friday social media post in Turkish.',
    false),
  ('Okula Dönüş', 'okula-donus', 'campaign', 'manual', 'back-to-school', 'medium',
    'Dinamik ve temiz ton.',
    '["Yeni döneme hazırız"]'::jsonb,
    '["Okula Dönüş"]'::jsonb,
    '["Hazırlık ve yeni dönem mesajı"]'::jsonb,
    'düzenli, modern, genç enerji',
    'fazla çocukça karakterler',
    'Create a clean Turkish back-to-school campaign post.',
    false),
  ('Dünya Kahve Günü', 'dunya-kahve-gunu', 'sectoral', 'fixed', '10-01', 'medium',
    'Sıcak ve davetkar ton.',
    '["Dünya Kahve Günü kutlu olsun"]'::jsonb,
    '["Dünya Kahve Günü"]'::jsonb,
    '["Kahve severlere sıcak mesaj"]'::jsonb,
    'kahve tonları, sıcak ve cozy',
    'karanlık, iştah kapatan görseller',
    'Create a warm Turkish World Coffee Day social post.',
    false)
on conflict (slug) do nothing;

insert into sector_modifiers (sector_key, sector_name, visual_cues, tone_hints, avoid_rules, prompt_modifier)
values
  ('beauty', 'Güzellik salonu', 'soft lighting, skincare textures', 'zarif, güven veren', 'aşırı kalabalık tasarım', 'elegant, feminine, polished, premium clean beauty aesthetic'),
  ('cafe', 'Kafe / restoran', 'coffee steam, warm tables', 'sıcak, davetkar', 'kirli masa hissi', 'warm, inviting, appetizing, cozy'),
  ('dental', 'Diş kliniği', 'clean whites, subtle clinical accents', 'temiz, profesyonel', 'rahatsız edici medikal detay', 'clean, trustworthy, hygienic, professional'),
  ('real-estate', 'Emlak ofisi', 'modern architecture, city outline', 'kendinden emin, modern', 'stok fotoğraf hissi', 'corporate, confident, modern, city lifestyle feel')
on conflict (sector_key) do nothing;

insert into style_modifiers (style_key, style_name, description, prompt_modifier)
values
  ('modern', 'Modern', 'Temiz, çağdaş, sosyal medya dostu.', 'clean, contemporary, social-first layout'),
  ('minimal', 'Minimal', 'Az metin, bol boşluk, sade tasarım.', 'minimal, spacious, refined typography'),
  ('corporate', 'Kurumsal', 'Güven veren, ciddi ve profesyonel.', 'trustworthy, formal, polished corporate feel'),
  ('friendly', 'Samimi', 'Sıcak, küçük işletme dostu.', 'warm, approachable, neighborhood business tone'),
  ('premium', 'Premium', 'Şık, kaliteli, ajans havasında.', 'luxury-inspired, elegant, agency-quality design'),
  ('colorful', 'Renkli / enerjik', 'Daha canlı, dikkat çekici.', 'energetic, vibrant, high-contrast social design')
on conflict (style_key) do nothing;
